/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.forms.admin;

import javax.swing.JFrame;

/**
 *
 * @author Bane
 */
public class AdminPanel extends javax.swing.JPanel {

    /**
     * Creates new form AdminPanel
     */
    public AdminPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane = new javax.swing.JTabbedPane();
        mealOfferPanel = new view.forms.admin.MealOfferPanel();
        employeesPanel = new view.forms.admin.EmployeesPanel();

        setPreferredSize(new java.awt.Dimension(1000, 640));

        mealOfferPanel.setPreferredSize(new java.awt.Dimension(840, 520));
        jTabbedPane.addTab("Ponude jela", mealOfferPanel);
        jTabbedPane.addTab("Zaposleni", employeesPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private view.forms.admin.EmployeesPanel employeesPanel;
    private javax.swing.JTabbedPane jTabbedPane;
    private view.forms.admin.MealOfferPanel mealOfferPanel;
    // End of variables declaration//GEN-END:variables
}
