/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.forms.admin;

import controller.Controller;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Employee;

/**
 *
 * @author Bane
 */
public class EmployeesPanel extends javax.swing.JPanel {

    /**
     * Creates new form EmployeesPanel
     */
    private List<Employee> employees;
    public EmployeesPanel() {
        initComponents();
        
        try {
            fillTable();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Greska prilikom ućitavanja podataka o zaposlenima");
            Logger.getLogger(EmployeesPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void fillTable() throws Exception {
        employees = Controller.getInstance().getEmployees();
        DefaultTableModel dtm = (DefaultTableModel) this.tableEmployees.getModel();
        int rows = dtm.getRowCount();
        if (rows >= 0) {
            for (int i = rows-1; i >= 0; i--) {
                dtm.removeRow(i);
            }
        }

        for (Employee e : employees) {
            String username = e.getAccount() == null ? "NEMA NALOG" : e.getAccount().getUsername();
            String accountStatus = e.getAccount() != null ? (e.getAccount().isActive() ? "Aktivan" : "Deaktiviran") : "NEMA NALOG";
            dtm.addRow(new Object[]{e.getImePrezime(), e.getJMBG(), e.getEmail(), username, accountStatus});
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableEmployees = new javax.swing.JTable();
        btnCreateAccount = new javax.swing.JButton();
        btnDeactivateAccount = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1000, 640));

        tableEmployees.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tableEmployees.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ime i Prezime", "JMBG", "Email", "Korisničko ime", "Status naloga"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableEmployees);

        btnCreateAccount.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btnCreateAccount.setText("Kreiraj nalog");
        btnCreateAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateAccountActionPerformed(evt);
            }
        });

        btnDeactivateAccount.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btnDeactivateAccount.setText("Deaktiviraj nalog");
        btnDeactivateAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeactivateAccountActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(715, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCreateAccount, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeactivateAccount, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 682, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(303, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCreateAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDeactivateAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(507, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 608, Short.MAX_VALUE)
                    .addContainerGap()))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateAccountActionPerformed
        int row = tableEmployees.getSelectedRow();
        if (row <= -1) {
            JOptionPane.showMessageDialog(this, "Morate izabrati nekog zaposlenog iz tabele");
            return;
        }

        Employee e = employees.get(row);
        if (e.getAccount() != null) {
            JOptionPane.showMessageDialog(this, "Zaposleni vec poseduje nalog");
            return;
        }

        new CreateAccountForm(null, true, e, this).setVisible(true);
    }//GEN-LAST:event_btnCreateAccountActionPerformed

    private void btnDeactivateAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeactivateAccountActionPerformed
        int row = tableEmployees.getSelectedRow();
        if (row <= -1) {
            JOptionPane.showMessageDialog(this, "Morate izabrati nekog zaposlenog iz tabele");
            return;
        }

        Employee e = employees.get(row);
        if (e.getAccount() == null) {
            JOptionPane.showMessageDialog(this, "Zaposleni ne poseduje nalog");
            return;
        }

        if (e.getAccount().isActive() == false) {
            JOptionPane.showMessageDialog(this, "Nalog zaposlenog je vec deaktiviran");
            return;
        }

        int response = JOptionPane.showConfirmDialog(this, "Da li sigurno želite da deaktivirate nalog zaposlenog:" + e.getImePrezime());
        // 0=yes, 1=no, 2=cancel
        if (response == JOptionPane.YES_OPTION) {
            try {
                Controller.getInstance().deactiveAccount(e.getAccount());
                JOptionPane.showMessageDialog(this, "Nalog uspešno dekativiran");
                this.fillTable();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Neuspešno deaktiviranje naloga");
            }
        } else {
            return;
        }
    }//GEN-LAST:event_btnDeactivateAccountActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateAccount;
    private javax.swing.JButton btnDeactivateAccount;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableEmployees;
    // End of variables declaration//GEN-END:variables
}
