/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.forms;

import controller.Controller;
import java.io.File;
import java.io.PrintWriter;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Meal;
import model.MealOffer;
import model.Order;

/**
 *
 * @author Bane
 */
public class OrderDetailsForm extends javax.swing.JDialog {

    /**
     * Creates new form OrderDetailsForm
     */
    private List<Order> orders;
    private MealOffer mealOffer;

    public OrderDetailsForm(java.awt.Frame parent, boolean modal, MealOffer mealOffer) throws Exception {
        super(parent, modal);
        initComponents();

        this.mealOffer = mealOffer;
        jLabel1.setText(jLabel1.getText() + " " + new SimpleDateFormat("dd.MM.yyyy").format(this.mealOffer.getDate()));
        orders = Controller.getInstance().getAllOrders(mealOffer);
        DefaultTableModel dtm = (DefaultTableModel) tableOrders.getModel();
        for (Order o : orders) {
            String[] tableRow = new String[]{o.getAccount().getEmployee().getImePrezime(), "", "", "", ""};
            for (Meal m : o.getOrderedMeals()) {
                switch (m.getType()) {
                    case PREDJELO:
                        tableRow[1] = m.getName();
                        if (m.getNumberOfPortions() > 1) {
                            tableRow[1] = m.getNumberOfPortions() + "x " + tableRow[1];
                        }
                        break;
                    case GLAVNO_JELO:
                        tableRow[2] = m.getName();
                        if (m.getNumberOfPortions() > 1) {
                            tableRow[2] = m.getNumberOfPortions() + "x " + tableRow[2];
                        }
                        break;
                    case SALATA:
                        tableRow[3] = m.getName();
                        if (m.getNumberOfPortions() > 1) {
                            tableRow[3] = m.getNumberOfPortions() + "x " + tableRow[3];
                        }
                        break;
                    case DEZERT:
                        tableRow[4] = m.getName();
                        if (m.getNumberOfPortions() > 1) {
                            tableRow[4] = m.getNumberOfPortions() + "x " + tableRow[4];
                        }
                        break;
                }
            }
            dtm.addRow(tableRow);
        }
        if (!Controller.getInstance().getUserAccount().isIsAdmin()) {
            btnCreateGroupOrder.setVisible(false);
        }
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableOrders = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnCreateGroupOrder = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tableOrders.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Zaposleni", "Predjelo", "Glavno jelo", "Salata", "Dezert"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableOrders);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setText("Pordžbina za datum:");

        btnCreateGroupOrder.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        btnCreateGroupOrder.setText("Kreiraj grupnu porudžbinu");
        btnCreateGroupOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateGroupOrderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(btnCreateGroupOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCreateGroupOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateGroupOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateGroupOrderActionPerformed
        String grupaPorudzbina;
        try {
            grupaPorudzbina = Controller.getInstance().createGroupOrder(this.mealOffer);
            JFileChooser fileChooser = new JFileChooser();
            fileChooser.setDialogTitle("Izaberite putanju na kojoj želite da sačuvate grupnu porudžbinu");
            int userSelection = fileChooser.showSaveDialog(this);
            if (userSelection == JFileChooser.APPROVE_OPTION) {
                File fileToSave = fileChooser.getSelectedFile();
                PrintWriter pw = new PrintWriter(fileToSave);
                pw.write(grupaPorudzbina);
                pw.flush();
                pw.close();
            }
            }catch (Exception ex) {
            Logger.getLogger(OrderDetailsForm.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Greška prilikom kreiranja grupne porudžbine");
            return;
        }
    }//GEN-LAST:event_btnCreateGroupOrderActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateGroupOrder;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableOrders;
    // End of variables declaration//GEN-END:variables
}
